import type { EditorThemeClasses } from "lexical";

export const editorTheme: EditorThemeClasses = {
  paragraph: "mb-1",
  heading: {
    h1: "text-2xl font-bold mb-2",
    h2: "text-xl font-bold mb-2",
    h3: "text-lg font-bold mb-1",
  },
  text: {
    bold: "font-bold",
    italic: "italic",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    subscript: "text-[0.8em] align-sub",
    superscript: "text-[0.8em] align-super",
    code: "bg-zinc-100 dark:bg-zinc-800 rounded px-1 py-0.5 font-mono text-[0.85em]",
  },
  quote:
    "border-l-4 border-zinc-300 dark:border-zinc-600 pl-4 italic text-zinc-600 dark:text-zinc-400 my-2",
  list: {
    nested: {
      listitem: "list-none",
    },
    ul: "list-disc ml-4 my-1",
    ol: "list-decimal ml-4 my-1",
    listitem: "my-0.5",
    listitemChecked:
      "line-through text-zinc-400 relative ml-2 list-none outline-none before:absolute before:-left-5 before:content-['✓'] before:text-green-500",
    listitemUnchecked:
      "relative ml-2 list-none outline-none before:absolute before:-left-5 before:content-['☐'] before:text-zinc-400",
  },
  code: "bg-zinc-100 dark:bg-zinc-800 rounded-lg p-3 font-mono text-sm my-2 block overflow-x-auto",
  codeHighlight: {
    atrule: "text-purple-600 dark:text-purple-400",
    attr: "text-blue-600 dark:text-blue-400",
    boolean: "text-orange-600 dark:text-orange-400",
    builtin: "text-cyan-600 dark:text-cyan-400",
    cdata: "text-zinc-500",
    char: "text-green-600 dark:text-green-400",
    class: "text-yellow-600 dark:text-yellow-400",
    "class-name": "text-yellow-600 dark:text-yellow-400",
    comment: "text-zinc-500 italic",
    constant: "text-orange-600 dark:text-orange-400",
    deleted: "text-red-600 dark:text-red-400",
    doctype: "text-zinc-500",
    entity: "text-orange-600 dark:text-orange-400",
    function: "text-blue-600 dark:text-blue-400",
    important: "text-orange-600 dark:text-orange-400 font-bold",
    inserted: "text-green-600 dark:text-green-400",
    keyword: "text-purple-600 dark:text-purple-400",
    namespace: "text-zinc-500",
    number: "text-orange-600 dark:text-orange-400",
    operator: "text-zinc-600 dark:text-zinc-400",
    prolog: "text-zinc-500",
    property: "text-blue-600 dark:text-blue-400",
    punctuation: "text-zinc-600 dark:text-zinc-400",
    regex: "text-green-600 dark:text-green-400",
    selector: "text-green-600 dark:text-green-400",
    string: "text-green-600 dark:text-green-400",
    symbol: "text-orange-600 dark:text-orange-400",
    tag: "text-red-600 dark:text-red-400",
    url: "text-blue-600 dark:text-blue-400 underline",
    variable: "text-orange-600 dark:text-orange-400",
  },
  link: "text-blue-600 dark:text-blue-400 underline cursor-pointer",
  table: "border-collapse w-full my-2",
  tableCell:
    "border border-zinc-300 dark:border-zinc-600 px-3 py-2 text-sm min-w-[75px]",
  tableCellHeader:
    "border border-zinc-300 dark:border-zinc-600 px-3 py-2 text-sm font-bold bg-zinc-100 dark:bg-zinc-800 min-w-[75px]",
  tableRow: "",
  horizontalRule: "border-t border-zinc-300 dark:border-zinc-600 my-4",
  image: "inline-block max-w-full",
  embedBlock: {
    base: "my-2",
    focus: "outline-2 outline-blue-500",
  },
};
