-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'FRIEND_REQUEST_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE 'CHAT_REQUEST';
ALTER TYPE "NotificationType" ADD VALUE 'CHAT_REQUEST_ACCEPTED';
